server:
  port: 3000
jwt:
  SECRET_KEY: my_s3cr3t_k3y
  DURATION: 10 # jwt duration in minutes
spring:
  sql:
    init:
      mode: always   # never # always
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  docker:
    compose:
      lifecycle-management: start_and_stop
      enabled: true

#documentation
springdoc:
  api:
    docs:
      enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
  